[package]
name = "kys_rust"
version = "0.1.0"
authors = ["Broly CJW <brolycjw@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.sdl2]
version = "0.32.0-beta.2"
default-features = false
features = ["image"]
