[package]
name = "kys_rust"
version = "0.1.0"
authors = ["Broly CJW <brolycjw@gmail.com>"]
edition = "2018"

[dependencies]
piston2d-opengl_graphics = "0.57.0"
byteorder = "1.2.7"
piston_window = "0.85.0"
find_folder = "0.3.0"
image = "0.20.0"
